name: States
version: '1.1.0'
main: org.hydr4.states.States
api-version: '1.20'
commands:
  states:
    description: Comando principale per il plugin States.
    usage: /<command> <create|trust|info>
    aliases: [state]
    permission: states.use
    permission-message: &cNon hai il permesso di utilizzare questo comando.